version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  ignore:
    - dependency-name: "*"
      update-types: [ "version-update:semver-patch" ]
    # Update these dependencies with CI (poetry update)
    - dependency-name: "colorama"
    # Update these dependencies with python-template
    - dependency-name: "omegaconf"
    - dependency-name: "structlog"
    ### Docs section ###
    - dependency-name: "sphinx"
    - dependency-name: "sphinx-autodoc-typehints"
    - dependency-name: "sphinxcontrib-apidoc"
    - dependency-name: "furo"
    - dependency-name: "m2r2"
    - dependency-name: "tomli"
    ### Dev section ###
    - dependency-name: "black"
    - dependency-name: "click"
    - dependency-name: "isort"
    - dependency-name: "pycln"
    - dependency-name: "doc8"
    - dependency-name: "pre-commit"
    - dependency-name: "mypy"
    - dependency-name: "flake8"
    - dependency-name: "flake8-docstrings"
    - dependency-name: "pydocstyle"
    - dependency-name: "safety"
    - dependency-name: "cruft"
    - dependency-name: "lice"
    - dependency-name: "pytest"
    - dependency-name: "pytest-cov"
    - dependency-name: "pytest-mock"
    - dependency-name: "pytest-testmon"
    - dependency-name: "pytest-randomly"
    - dependency-name: "Faker"
    - dependency-name: "GitPython"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
