name: Bug Report
description: Something works wrong?
labels: "needs triage,bug"

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        A detailed and clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What expected?
      description: >-
        A detailed and clear description of what you expected to happen.

  - type: input
    id: commit_repo
    attributes:
      label: Repository's commit
      placeholder: cd the-war-tracker-bot; git rev-parse HEAD
    validations:
      required: true
  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: python -V
    validations:
      required: true
  - type: input
    id: poetry_version
    attributes:
      label: poetry version
      placeholder: poetry version
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: Please write detailed steps to reproduce the error.
      placeholder: |
        1. Change line ...
        2. Then run ...
        3. And error happens.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Provide all logs when error happens.
      render: sh-session

  - type: checkboxes
    id: checkboxes
    attributes:
      label: This isn't a duplicate
      options:
        - label: In repository and Internet there is no duplicate of this error.
          required: true
